// <auto-generated />
using System;
using LektionVinuylCollection.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LektionVinuylCollection.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211215180034_seed_data_for_artists")]
    partial class seed_data_for_artists
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("LektionVinuylCollection.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FavoriteCar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 12, 15, 19, 0, 34, 355, DateTimeKind.Local).AddTicks(390),
                            FavoriteCar = "Benz",
                            Name = "Artist 1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 12, 15, 19, 0, 34, 355, DateTimeKind.Local).AddTicks(1650),
                            FavoriteCar = "Volvo",
                            Name = "Artist 2"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 12, 15, 19, 0, 34, 355, DateTimeKind.Local).AddTicks(1660),
                            FavoriteCar = "Volkswagen",
                            Name = "Artist 3"
                        });
                });

            modelBuilder.Entity("LektionVinuylCollection.Entities.Vinyl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArtistID");

                    b.ToTable("Vinyls");
                });

            modelBuilder.Entity("LektionVinuylCollection.Entities.Vinyl", b =>
                {
                    b.HasOne("LektionVinuylCollection.Entities.Artist", "Artist")
                        .WithMany("Vinyls")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("LektionVinuylCollection.Entities.Artist", b =>
                {
                    b.Navigation("Vinyls");
                });
#pragma warning restore 612, 618
        }
    }
}
